jquery_lang_js.prototype.lang.pt = {
	'Battery: ':'Bateria: ',
	'Model: ':'Modelo: ',
	'Color Sensor: ':'Sensor de Cor: ',
	'Speed: ':'Velocidade: ',
	'DEBUG Counter: ':'Contador DEBUG: ',
	'Clock: ':'Relógio: ',
	'NXTBrowser by ':'NXTBrowser por ',
	'L' : 'E',
	'R' : 'D',
	'F' : 'F',
	'Stop' : 'Stop',
	'Wifi Speed: ': 'Vel. Wifi: ',
	'Mobile: ': 'Móvel: ',
	'Mobile Type: ':'Tipo Móvel: ',
	'Error communicating to webserver - disable timer':'Erro na comunicação com o servidor - timer desabilitado',
	'operator' : 'operador',
	'SELF' : 'SELF',
};
